feat: assembler e disassembler de orders + integration tests

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -12,5 +12,14 @@ if [ $RESULT -ne 0 ]; then
   exit 1
 fi
 
+gradle integrationTest
+
+RESULT=$?
+
+if [ $RESULT -ne 0 ]; then
+  echo "❌ Tests failed. Commit aborted."
+  exit 1
+fi
+
 echo "✅ Tests passed. Proceeding with commit."
 exit 0
